name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]   # change to 'master' if that's your default

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd Blog-viteProject
          npm install

      - name: Build
        run: |
          cd Blog-viteProject
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Blog-viteProject/dist
